github: [talafek96]
patreon: # Replace with a single Patreon username
ko_fi: joshiminh
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
